//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleCopCLI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleCopCLI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flags.
        /// </summary>
        internal static string ConfigurationFlagsSwitchArgumentName {
            get {
                return ResourceManager.GetString("ConfigurationFlagsSwitchArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration flags to use during analysis (e.g. DEBUG, RELEASE)..
        /// </summary>
        internal static string ConfigurationFlagsSwitchDescription {
            get {
                return ResourceManager.GetString("ConfigurationFlagsSwitchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurationFlags.
        /// </summary>
        internal static string ConfigurationFlagsSwitchLongName {
            get {
                return ResourceManager.GetString("ConfigurationFlagsSwitchLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print this help screen..
        /// </summary>
        internal static string HelpSwitchDescription {
            get {
                return ResourceManager.GetString("HelpSwitchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string HelpSwitchLongName {
            get {
                return ResourceManager.GetString("HelpSwitchLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No source code files to analyze..
        /// </summary>
        internal static string NoFilesToAnalyze {
            get {
                return ResourceManager.GetString("NoFilesToAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filePath.
        /// </summary>
        internal static string OutputFileSwitchArgumentName {
            get {
                return ResourceManager.GetString("OutputFileSwitchArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file to write analysis results to..
        /// </summary>
        internal static string OutputFileSwitchDescription {
            get {
                return ResourceManager.GetString("OutputFileSwitchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outputFile.
        /// </summary>
        internal static string OutputFileSwitchLongName {
            get {
                return ResourceManager.GetString("OutputFileSwitchLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filePaths.
        /// </summary>
        internal static string ProjectFilesSwitchArgumentName {
            get {
                return ResourceManager.GetString("ProjectFilesSwitchArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual C# project (*.csproj) files referencing Visual C# source files to analyze..
        /// </summary>
        internal static string ProjectFilesSwitchDescription {
            get {
                return ResourceManager.GetString("ProjectFilesSwitchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projectFiles.
        /// </summary>
        internal static string ProjectFilesSwitchLongName {
            get {
                return ResourceManager.GetString("ProjectFilesSwitchLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursively search subdirectories for files to analyze..
        /// </summary>
        internal static string RecursiveSearchSwitchDescription {
            get {
                return ResourceManager.GetString("RecursiveSearchSwitchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recursiveSearch.
        /// </summary>
        internal static string RecursiveSearchSwitchLongName {
            get {
                return ResourceManager.GetString("RecursiveSearchSwitchLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filePath.
        /// </summary>
        internal static string SettingsFileSwitchArgumentName {
            get {
                return ResourceManager.GetString("SettingsFileSwitchArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleCop settings file to use during analysis..
        /// </summary>
        internal static string SettingsFileSwitchDescription {
            get {
                return ResourceManager.GetString("SettingsFileSwitchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settingsFile.
        /// </summary>
        internal static string SettingsFileSwitchLongName {
            get {
                return ResourceManager.GetString("SettingsFileSwitchLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filePaths.
        /// </summary>
        internal static string SolutionFilesSwitchArgumentName {
            get {
                return ResourceManager.GetString("SolutionFilesSwitchArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio solution (*.sln) files indirectly referencing Visual C# source files to analyze..
        /// </summary>
        internal static string SolutionFilesSwitchDescription {
            get {
                return ResourceManager.GetString("SolutionFilesSwitchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to solutionFiles.
        /// </summary>
        internal static string SolutionFilesSwitchLongName {
            get {
                return ResourceManager.GetString("SolutionFilesSwitchLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filePaths.
        /// </summary>
        internal static string SourceFilesSwitchArgumentName {
            get {
                return ResourceManager.GetString("SourceFilesSwitchArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual C# source (*.cs) files to analyze..
        /// </summary>
        internal static string SourceFilesSwitchDescription {
            get {
                return ResourceManager.GetString("SourceFilesSwitchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sourceFiles.
        /// </summary>
        internal static string SourceFilesSwitchLongName {
            get {
                return ResourceManager.GetString("SourceFilesSwitchLongName", resourceCulture);
            }
        }
    }
}
